name: Build Rust
run-name: Rust build triggered by ${{ github.actor }}
on:
  push:
    paths:
      - 'src/api/**'
      - 'Cargo.toml'
      - '.github/workflows/build-rust.yml'
  pull_request:
    paths:
      - 'src/api/**'
      - 'Cargo.toml'
      - '.github/workflows/build-rust.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
    Build-Rust:
        runs-on: ubuntu-latest
        steps:
            - name: Check out branch ${{ github.ref }} from ${{ github.repository }}
              uses: actions/checkout@v4

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable

            - name: Build Rust project
              run: cargo build --verbose --release --all-features

            - name: Run unit tests
              run: cargo test --verbose
            
            - name: Install wasm-pack CLI tool
              run: cargo install wasm-pack
            
            - name: Update wasm module
              run: wasm-pack build --target bundler
