name: Build Rust
run-name: Rust build triggered by ${{ github.actor }}
on:
  push:
    branches: [ $default-branch ]
    paths:
      - 'src/api/*'
      - 'Cargo.toml'
  pull_request:
    branches: [ $default-branch ]
    paths:
      - 'src/api/*'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
    Build-Rust:
        runs-on: ubuntu-latest
        steps:
            - name: Check out branch ${{ github.ref }} from ${{ github.repository }}
              uses: actions/checkout@v4

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable

            - name: Build Rust project
              run: cargo build --verbose --release --all-features

            - name: Run unit tests
              run: cargo test --verbose
