name: Build Vue
run-name: Vue build triggered by ${{ github.actor }}
on:
    push:
      paths:
        - 'public/**'
        - 'src/ui/**'
        - 'index.html'
        - 'package.json'
        - '.github/workflows/build-vue.yml'
    pull_request:
      paths:
        - 'public/**'
        - 'src/ui/**'
        - 'index.html'
        - 'package.json'
        - '.github/workflows/build-vue.yml'

jobs:
    Build-Vue:
        runs-on: ubuntu-latest
        steps:
            - name: Check out branch ${{ github.ref }} from ${{ github.repository }}
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 9

            - name: Install dependencies
              run: pnpm install

            - name: Build Vue project
              run: pnpm build

            - name: Run unit tests
              run: pnpm exec vitest
