name: Build Rust
run-name: Rust build triggered by ${{ github.actor }}
on: [push]
jobs:
    Build-Rust:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
            - run: cargo build --release --all-features
